services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sciber_user
      POSTGRES_PASSWORD: sciber_pass
      POSTGRES_DB: sciber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./storage:/app/storage
    environment:
      - ENABLE_IN_PROCESS_WATCHER_SYNC=false
      - WATCHER_DEBOUNCE_SECONDS=${WATCHER_DEBOUNCE_SECONDS:-1.5}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "app.tasks.core.celery_app", "worker", "--loglevel=info", "--pool=solo"]
    volumes:
      - ./storage:/app/storage
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "app.tasks.core.celery_app", "beat", "--loglevel=info"]
    volumes:
      - ./storage:/app/storage
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
