"""Add unique constraint on filename and whisper_model in audio_files

Revision ID: 56c2eac6ebd6
Revises: 6d08ddfb8789
Create Date: 2025-08-24 20:45:37.232189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c2eac6ebd6'
down_revision: Union[str, Sequence[str], None] = '6d08ddfb8789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_filename_whisper_model', 'audio_files', ['filename', 'whisper_model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_filename_whisper_model', 'audio_files', type_='unique')
    # ### end Alembic commands ###
