"""Добавление уникального ограничения на сочетание filename + whisper_model.

Автосгенерированная миграция Alembic. Докстринг добавлен для документирования
цели миграции; код миграции не менялся.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c2eac6ebd6'
down_revision: Union[str, Sequence[str], None] = '6d08ddfb8789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_filename_whisper_model', 'audio_files', ['filename', 'whisper_model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_filename_whisper_model', 'audio_files', type_='unique')
    # ### end Alembic commands ###
