"""Добавление каскадного удаления между связанными таблицами.

Эта миграция изменяет внешние ключи, чтобы удаление аудиофайла автоматически
удалял связанные расшифровки, переводы и резюме (ON DELETE CASCADE).
"""
from typing import Sequence, Union, cast

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d08ddfb8789'
down_revision: Union[str, Sequence[str], None] = '9e955ac193bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('summaries_translation_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(cast(str, None), 'summaries', 'translations', ['translation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transcripts_audio_file_id_fkey'), 'transcripts', type_='foreignkey')
    op.create_foreign_key(cast(str, None), 'transcripts', 'audio_files', ['audio_file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('translations_transcript_id_fkey'), 'translations', type_='foreignkey')
    op.create_foreign_key(cast(str, None), 'translations', 'transcripts', ['transcript_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(cast(str, None), 'translations', type_='foreignkey')
    op.create_foreign_key(op.f('translations_transcript_id_fkey'), 'translations', 'transcripts', ['transcript_id'], ['id'])
    op.drop_constraint(cast(str, None), 'transcripts', type_='foreignkey')
    op.create_foreign_key(op.f('transcripts_audio_file_id_fkey'), 'transcripts', 'audio_files', ['audio_file_id'], ['id'])
    op.drop_constraint(cast(str, None), 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_translation_id_fkey'), 'summaries', 'translations', ['translation_id'], ['id'])
    # ### end Alembic commands ###
