"""add transcript_id to translation

Revision ID: 9e955ac193bb
Revises: d02885245d0b
Create Date: 2025-08-24 16:36:57.762019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e955ac193bb'
down_revision: Union[str, Sequence[str], None] = 'd02885245d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('transcript_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'translations', ['transcript_id'])
    op.create_foreign_key(None, 'translations', 'transcripts', ['transcript_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_constraint(None, 'translations', type_='unique')
    op.drop_column('translations', 'transcript_id')
    # ### end Alembic commands ###
