"""Добавление поля transcript_id в таблицу translations.

Автосгенерированная миграция; добавляет связь между переводом и расшифровкой.
"""
from typing import Sequence, Union, cast

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e955ac193bb'
down_revision: Union[str, Sequence[str], None] = 'd02885245d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('transcript_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(cast(str, None), 'translations', ['transcript_id'])
    op.create_foreign_key(cast(str, None), 'translations', 'transcripts', ['transcript_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(cast(str, None), 'translations', type_='foreignkey')
    op.drop_constraint(cast(str, None), 'translations', type_='unique')
    op.drop_column('translations', 'transcript_id')
    # ### end Alembic commands ###
