"""Remove unique from filename, add unique constraint on filename and whisper_model

Revision ID: f1ceca8f974f
Revises: 56c2eac6ebd6
Create Date: 2025-08-24 20:52:08.083453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ceca8f974f'
down_revision: Union[str, Sequence[str], None] = '56c2eac6ebd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_files_filename_key'), 'audio_files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('audio_files_filename_key'), 'audio_files', ['filename'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
